name: bluemart
description: "Aplikasi Retail UMKM - Project Akhir PPB"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.4
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.3
  sensors_plus: ^7.1.0
  http: ^1.3.0
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  provider: ^6.1.2
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
  local_auth: ^2.3.0
  flutter_ringtone_player: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true